/**
 * SpaceX REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CapsuleMission } from './capsuleMission';
import { Dragon } from './dragon';


export interface Capsule { 
    id?: any;
    landings?: number;
    missions?: Array<CapsuleMission>;
    originalLaunch?: any;
    reuseCount?: number;
    status?: string;
    type?: string;
    dragon?: Dragon;
}
