/**
 * SpaceX REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Distance } from './distance';
import { DragonHeatShield } from './dragonHeatShield';
import { DragonPressurizedCapsule } from './dragonPressurizedCapsule';
import { DragonThrust } from './dragonThrust';
import { DragonTrunk } from './dragonTrunk';
import { Mass } from './mass';
import { Volume } from './volume';


export interface Dragon { 
    active?: boolean;
    crewCapacity?: number;
    description?: string;
    diameter?: Distance;
    dryMassKg?: number;
    dryMassLb?: number;
    firstFlight?: string;
    heatShield?: DragonHeatShield;
    heightWTrunk?: Distance;
    id?: any;
    launchPayloadMass?: Mass;
    launchPayloadVol?: Volume;
    name?: string;
    orbitDurationYr?: number;
    pressurizedCapsule?: DragonPressurizedCapsule;
    returnPayloadMass?: Mass;
    returnPayloadVol?: Volume;
    sidewallAngleDeg?: number;
    thrusters?: Array<DragonThrust>;
    trunk?: DragonTrunk;
    type?: string;
    wikipedia?: string;
}
