/**
 * SpaceX REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Launch } from './launch';
import { Link } from './link';


export interface History { 
    details?: string;
    eventDateUnix?: any;
    eventDateUtc?: any;
    id?: any;
    links?: Link;
    title?: string;
    flight?: Launch;
}
