/**
 * SpaceX REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Location } from './location';


export interface Landpad { 
    attemptedLandings?: string;
    details?: string;
    fullName?: string;
    id?: any;
    landingType?: string;
    location?: Location;
    status?: string;
    successfulLandings?: string;
    wikipedia?: string;
}
