/**
 * SpaceX REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface LaunchFind { 
    apoapsisKm?: number;
    block?: number;
    capSerial?: string;
    capsuleReuse?: string;
    coreFlight?: number;
    coreReuse?: string;
    coreSerial?: string;
    customer?: string;
    eccentricity?: number;
    end?: any;
    epoch?: any;
    fairingsRecovered?: string;
    fairingsRecoveryAttempt?: string;
    fairingsReuse?: string;
    fairingsReused?: string;
    fairingsShip?: string;
    gridfins?: string;
    id?: any;
    inclinationDeg?: number;
    landSuccess?: string;
    landingIntent?: string;
    landingType?: string;
    landingVehicle?: string;
    launchDateLocal?: any;
    launchDateUtc?: any;
    launchSuccess?: string;
    launchYear?: string;
    legs?: string;
    lifespanYears?: number;
    longitude?: number;
    manufacturer?: string;
    meanMotion?: number;
    missionId?: string;
    missionName?: string;
    nationality?: string;
    noradId?: number;
    orbit?: string;
    payloadId?: string;
    payloadType?: string;
    periapsisKm?: number;
    periodMin?: number;
    raan?: number;
    referenceSystem?: string;
    regime?: string;
    reused?: string;
    rocketId?: string;
    rocketName?: string;
    rocketType?: string;
    secondStageBlock?: string;
    semiMajorAxisKm?: number;
    ship?: string;
    sideCore1Reuse?: string;
    sideCore2Reuse?: string;
    siteId?: string;
    siteNameLong?: string;
    siteName?: string;
    start?: any;
    tbd?: string;
    tentativeMaxPrecision?: string;
    tentative?: string;
}
