/**
 * SpaceX REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LaunchRocketFairings } from './launchRocketFairings';
import { LaunchRocketFirstStage } from './launchRocketFirstStage';
import { LaunchRocketSecondStage } from './launchRocketSecondStage';
import { Rocket } from './rocket';


export interface LaunchRocket { 
    fairings?: LaunchRocketFairings;
    firstStage?: LaunchRocketFirstStage;
    rocketName?: string;
    rocketType?: string;
    rocket?: Rocket;
    secondStage?: LaunchRocketSecondStage;
}
