/**
 * SpaceX REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Location } from './location';
import { Rocket } from './rocket';


export interface Launchpad { 
    attemptedLaunches?: number;
    details?: string;
    id?: any;
    location?: Location;
    name?: string;
    status?: string;
    successfulLaunches?: number;
    vehiclesLaunched?: Array<Rocket>;
    wikipedia?: string;
}
