/**
 * SpaceX REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface LaunchLinks { 
    articleLink?: string;
    flickrImages?: Array<string>;
    missionPatchSmall?: string;
    missionPatch?: string;
    presskit?: string;
    redditCampaign?: string;
    redditLaunch?: string;
    redditMedia?: string;
    redditRecovery?: string;
    videoLink?: string;
    wikipedia?: string;
}
