/**
 * SpaceX REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LaunchLinks } from './launchLinks';
import { LaunchRocket } from './launchRocket';
import { LaunchSite } from './launchSite';
import { LaunchTelemetry } from './launchTelemetry';
import { Ship } from './ship';


export interface Launch { 
    details?: string;
    id?: any;
    isTentative?: boolean;
    launchDateLocal?: any;
    launchDateUnix?: any;
    launchDateUtc?: any;
    launchSite?: LaunchSite;
    launchSuccess?: boolean;
    launchYear?: string;
    links?: LaunchLinks;
    missionId?: Array<string>;
    missionName?: string;
    rocket?: LaunchRocket;
    staticFireDateUnix?: any;
    staticFireDateUtc?: any;
    telemetry?: LaunchTelemetry;
    tentativeMaxPrecision?: string;
    upcoming?: boolean;
    ships?: Array<Ship>;
}
