/**
 * SpaceX REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Payload } from './payload';


export interface Mission { 
    description?: string;
    id?: any;
    manufacturers?: Array<string>;
    name?: string;
    twitter?: string;
    website?: string;
    wikipedia?: string;
    payloads?: Array<Payload>;
}
