/**
 * SpaceX REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PayloadOrbitParams } from './payloadOrbitParams';


export interface Payload { 
    customers?: Array<string>;
    id?: any;
    manufacturer?: string;
    nationality?: string;
    noradId?: Array<number>;
    orbitParams?: PayloadOrbitParams;
    orbit?: string;
    payloadMassKg?: number;
    payloadMassLbs?: number;
    payloadType?: string;
    reused?: boolean;
}
