/**
 * SpaceX REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PayloadOrbitParams { 
    apoapsisKm?: number;
    argOfPericenter?: number;
    eccentricity?: number;
    epoch?: any;
    inclinationDeg?: number;
    lifespanYears?: number;
    longitude?: number;
    meanAnomaly?: number;
    meanMotion?: number;
    periapsisKm?: number;
    periodMin?: number;
    raan?: number;
    referenceSystem?: string;
    regime?: string;
    semiMajorAxisKm?: number;
}
