/**
 * SpaceX REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Capsule } from './capsule';
import { Core } from './core';
import { Dragon } from './dragon';
import { HistoriesResult } from './historiesResult';
import { History } from './history';
import { Info } from './info';
import { Landpad } from './landpad';
import { Launch } from './launch';
import { LaunchesPastResult } from './launchesPastResult';
import { Launchpad } from './launchpad';
import { Mission } from './mission';
import { MissionResult } from './missionResult';
import { Payload } from './payload';
import { Roadster } from './roadster';
import { Rocket } from './rocket';
import { RocketsResult } from './rocketsResult';
import { Ship } from './ship';
import { ShipsResult } from './shipsResult';
import { Users } from './users';
import { UsersAggregate } from './usersAggregate';


export interface Query { 
    capsule?: Capsule;
    capsules?: Array<Capsule>;
    capsulesPast?: Array<Capsule>;
    capsulesUpcoming?: Array<Capsule>;
    company?: Info;
    core?: Core;
    cores?: Array<Core>;
    coresPast?: Array<Core>;
    coresUpcoming?: Array<Core>;
    dragon?: Dragon;
    dragons?: Array<Dragon>;
    histories?: Array<History>;
    historiesResult?: HistoriesResult;
    history?: History;
    landpad?: Landpad;
    landpads?: Array<Landpad>;
    launch?: Launch;
    launchLatest?: Launch;
    launchNext?: Launch;
    launches?: Array<Launch>;
    launchesPast?: Array<Launch>;
    launchesPastResult?: LaunchesPastResult;
    launchesUpcoming?: Array<Launch>;
    launchpad?: Launchpad;
    launchpads?: Array<Launchpad>;
    mission?: Mission;
    missions?: Array<Mission>;
    missionsResult?: MissionResult;
    payload?: Payload;
    payloads?: Array<Payload>;
    roadster?: Roadster;
    rocket?: Rocket;
    rockets?: Array<Rocket>;
    rocketsResult?: RocketsResult;
    ship?: Ship;
    ships?: Array<Ship>;
    shipsResult?: ShipsResult;
    users: Array<Users>;
    usersAggregate: UsersAggregate;
    usersByPk?: Users;
}
