/**
 * SpaceX REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Roadster { 
    apoapsisAu?: number;
    details?: string;
    earthDistanceKm?: number;
    earthDistanceMi?: number;
    eccentricity?: number;
    epochJd?: number;
    inclination?: number;
    launchDateUnix?: any;
    launchDateUtc?: any;
    launchMassKg?: number;
    launchMassLbs?: number;
    longitude?: number;
    marsDistanceKm?: number;
    marsDistanceMi?: number;
    name?: string;
    noradId?: number;
    orbitType?: number;
    periapsisArg?: number;
    periapsisAu?: number;
    periodDays?: number;
    semiMajorAxisAu?: number;
    speedKph?: number;
    speedMph?: number;
    wikipedia?: string;
}
