/**
 * SpaceX REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Distance } from './distance';
import { Mass } from './mass';
import { RocketEngines } from './rocketEngines';
import { RocketFirstStage } from './rocketFirstStage';
import { RocketLandingLegs } from './rocketLandingLegs';
import { RocketPayloadWeight } from './rocketPayloadWeight';
import { RocketSecondStage } from './rocketSecondStage';


export interface Rocket { 
    active?: boolean;
    boosters?: number;
    company?: string;
    costPerLaunch?: number;
    country?: string;
    description?: string;
    diameter?: Distance;
    engines?: RocketEngines;
    firstFlight?: any;
    firstStage?: RocketFirstStage;
    height?: Distance;
    id?: any;
    landingLegs?: RocketLandingLegs;
    mass?: Mass;
    name?: string;
    payloadWeights?: Array<RocketPayloadWeight>;
    secondStage?: RocketSecondStage;
    stages?: number;
    successRatePct?: number;
    type?: string;
    wikipedia?: string;
}
