/**
 * SpaceX REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Force } from './force';


export interface RocketEngines { 
    number?: number;
    type?: string;
    version?: string;
    layout?: string;
    engineLossMax?: string;
    propellant1?: string;
    propellant2?: string;
    thrustSeaLevel?: Force;
    thrustVacuum?: Force;
    thrustToWeight?: number;
}
