/**
 * SpaceX REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ShipsFind { 
    id?: any;
    name?: string;
    model?: string;
    type?: string;
    role?: string;
    active?: boolean;
    imo?: number;
    mmsi?: number;
    abs?: number;
    _class?: number;
    weightLbs?: number;
    weightKg?: number;
    yearBuilt?: number;
    homePort?: string;
    status?: string;
    speedKn?: number;
    courseDeg?: number;
    latitude?: number;
    longitude?: number;
    successfulLandings?: number;
    attemptedLandings?: number;
    mission?: string;
}
