/**
 * SpaceX REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface StringComparisonExp { 
    eq?: string;
    gt?: string;
    gte?: string;
    ilike?: string;
    _in?: Array<string>;
    isNull?: boolean;
    like?: string;
    lt?: string;
    lte?: string;
    neq?: string;
    nilike?: string;
    nin?: Array<string>;
    nlike?: string;
    nsimilar?: string;
    similar?: string;
}
