/**
 * SpaceX REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TimestamptzComparisonExp { 
    eq?: any;
    gt?: any;
    gte?: any;
    _in?: Array<any>;
    isNull?: boolean;
    lt?: any;
    lte?: any;
    neq?: any;
    nin?: Array<any>;
}
